### PR TITLE
Fixes StackOverflowError thrown on Mac for large command sequences

### PR DESCRIPTION
**Pull request by jakubsadura**
For Mac OS execution of commands is batched for no more than 50 commands per frame. This helps to avoid StackOverflowError which could have been thrown for execution of large (>100 commands) sequence of commands in single frame which would exceed default recursion limit.

@jenshalm please review

### CODE REVIEW

**Comment by jenshalm** [comment]
Hi Jakub, I am sorry, but I stopped maintaining these projects more than 3 years ago. The only reason that the code is still available in this repo, is to allow others to fork it should they wish to continue the work in a different repo.

**Comment by spicefactory** [comment]
Hi Jakub, I am sorry, but I stopped maintaining these projects more than 3 years ago. The only reason that the code is still available in this repo, is to allow others to fork it should they wish to continue the work in a different repo.

**Comment by jakubsadura** [comment]
@spicefactory no worries, thanks for the reply :)

**Comment by spamshaker** [comment]
@jakubsadura This is rather Adobe AIR bug, and the solution is the workaround. Anyone who face this problem can find it here. Maybe better will be to report it to Adobe

**Pull request closed without merging**
